#!/bin/bash
# https://github.com/stuartpb/aur.so
#
# sudo pacman -S $(pacman -Qqe) --noconfirm
# remove
# sudo pacman -Rd $(pacman -Q --deps --unrequired --quiet)
# pacman -S archlinux-xdg-menu

# # Remove unused packages
# pacman -Rns $(pacman -Qtdq)
# # Remove cached versions of uninstalled packages
# paccache -ruk0
# # define how many recent versions you want to keep
# paccache -rk 2
# # deletes all cached versions of each package regardless of whether they're installed or not, except for the most recent 3, by default:
# paccache -r


cur=`pwd`

ver() {
	tmp=`mktemp`
	code=`curl -so $tmp -w "%{http_code}" "https://aur.archlinux.org/cgit/aur.git/plain/PKGBUILD?h=$1"`
	if [ "$code" != "200" ]; then
		echo "Failed to get $1 version. Status $code" >&2
	else
		. $tmp
		echo $pkgver-$pkgrel
	fi
	rm $tmp
}

build() {
	tmp=`mktemp -d`
	cd $tmp
	#curl "https://aur.archlinux.org/packages/${1%"${1#??}"}/$1/$1.tar.gz" | tar xz
	curl "https://aur.archlinux.org/cgit/aur.git/snapshot/$1.tar.gz" | tar xz
	cd $1
	makepkg -si
	pkg=$(makepkg --packagelist)
	#sudo pacman -U $1-*.pkg.tar*
	sudo cp $1-*.pkg.tar* /var/cache/pacman/pkg/
	#find $tmp/$1 -maxdepth 1 -name "$1-*.pkg.tar.xz" -exec sudo pacman -U "file://{}" \;
	#echo sudo pacman -U file://$PWD/$1-*.pkg.tar.xz
	#cd $cur
	#rm -rf $tmp
}

if [ $# -eq 0 ]; then
	pacman -Qem | while read name ver; do
		ver=${ver#?:}
		next_ver=`ver $name`
		if [ -n "$next_ver" -a "$next_ver" != "$ver" ]; then
			printf "Update $name from $ver to $next_ver\n"
			#build $name
		fi
	done

	exit
fi




for name; do
	build "$name"
done

